### PR TITLE
Fix chat to be visible when using custom trigger to open

### LINKED ISSUE #2258: In some situations the chat button is visible without a active websocket connection
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): Ubuntu Package
* Operating system: Ubuntu 16.04 Server
* Database + version: MySQL 5.7.23
* Elasticsearch version: 5.6.12
* Browser + version: Chrome 69.0.3497.100 

### Expected behavior:

Chat button should not be visible when websocket connection was closed (because of to long idle time).

### Actual behavior:

When the page with the implemented chat stays longer open/idle i get the message in the console **WebSocket is already in CLOSING or CLOSED state.** when clicking the custom trigger to open the chat.

### Steps to reproduce the behavior:

Implement chat with parameter **show: false** 

```
new ZammadChat({
    fontSize: '12px',
    chatId: 1,
    show: false
    idleTimeout: 1
});
```

use a custom trigger like:
```<button class="open-zammad-chat">Chat with us</button>```

Wait one minute and see that the button is still visible after the websocket connection was closed, because of the reached idle time. If you click on the button, nothing will be happen and you see a error message in the log.

### PR DESCRIPTION
**Pull request by rodrigo-morais**
This PR fixes the issue #2258 when `ZammadChat` widget is created with `show = false` as option and a click on the button does not make the chat visible.

### CODE REVIEW

**Comment by emper0r** [comment]
I can confirm, that not work, I hope PR solve this, waiting for upgrade, 

BUT using in automatic way not work either.

I just installed from zammad debian packaged using fresh install, just activate chat option, in the same LAN without firewalls, create this simple test.html

and not work with operator online.

<html>
<title>chat zammad</title>
<body>
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://192.168.0.1/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    background: '#3c4041',
    fontSize: '12px',
    chatId: 1
  });
});
</script>
</script>
</body>

**Comment by emper0r** [comment]
This pull request not works... I confirm 8 days ago, have 2 updates of zammad packages and still not working or this pull still not integrated into code repo for package. Zammad Chat not work please fix it!

**Comment by mrflix** [comment]
Hey @emper0r, it looks like your problem is not connected to this pull request. Please head over to https://community.zammad.org to discuss problems when setting up Zammad. Please fill a separate issue if the issues that appear in your setup exist because of a bug in the chat.

**Comment by thorsteneckel** [comment]
Hi @mrflix - is there anything stopping us from merging this PR?

**Comment by martini** [comment]
closed by accident - re-open

**Comment by mantas** [comment]
Looks like this is already fixed since the PR was submitted. Closing this PR now.

**Pull request closed without merging**
