### PR TITLE
Fix typo in timezone.coffee

### PR DESCRIPTION
**Pull request by maxxer**

### CODE REVIEW

**Comment by SummerStorm** [comment]
Hi, there. Thanks for the contribution. Since this is straightforward typo fix it should be merged fairly quickly. 

### Info for developers
This is currently undergoing CI as internal branch: https://git.znuny.com/zammad/zammad/commits/private-pr2625

**Comment by thorsteneckel** [comment]
@dennybresch - can you please check if and how this affects the i18 server?

**Comment by dennykorsukewitz** [comment]
'Enter timezone...' is currently not available on the i18 server.
I will push it manually and add it to the master and also delete the old wrong translation.

**Comment by SummerStorm** [comment]
Merged via 4d0c618baa71ce2ee52a9b08cf33e0fefd6b7356 on `develop` and 7e72474c0788a16d35304ba9f9fb9fbfd5a7f64b on `stable`.

Thanks again for your contribution!

**Pull request closed without merging**
