### PR TITLE
Tell Internet Explorer to display content in the highest mode available.

### PR DESCRIPTION
**Pull request by IAmWebSA**
This shall solve issues like Company Profiles setting to a lower document mode per default, that prevents the page to be loaded  for e.g.  IE document mode 7 etc.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @mrflix / @martini - as stated [here](https://stackoverflow.com/a/6771584/7900866) there should be no need for this if we are only supporting IE 11 and Edge. As far as I can remember we also have the support for IE 10, right? What do you think?

**Comment by mrflix** [comment]
@IAmWebSA what's your use case? Are you working in a company where you use IE10 with a document mode of IE7? We support IE >= 10.

**Comment by IAmWebSA** [comment]
Yes exactly, the mode is set for compatibility reasons in IE11. So telling the mode for IE would be a great addition. To Auto use the latest mode.

**Comment by IAmWebSA** [comment]
I have fixed the intention. Thanks for integrating the change

**Comment by thorsteneckel** [comment]
Merged with the commits above. Thanks for your contribution!

**Pull request merged**
