### PR TITLE
Move calendar mapping to config directory

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by monotek** [comment]
Whats the reason to move this to a file?
Imho it's easier for the user if he is able to do most of the configuration through the frontend.

**Comment by corny** [comment]
Because it's not a part of the (business) logic and blows up the model. Files of several hundred lines of code should be also splitted in mid-term. [ActiveSupport::Concern](http://api.rubyonrails.org/classes/ActiveSupport/Concern.html) is the way to go.

**Comment by corny** [comment]
This commit does not change logic. It just removes the data from the `model` directory.

**Comment by martini** [comment]
@monotek you still can use the ui for edit/changing -> It's just the ical feed list for the different countries.

**Pull request merged**
