### PR TITLE
backup: stop using su for pg_dump

### PR DESCRIPTION
**Pull request by nijel**
* It creates files owned by postgres user which cannot be later moved to correct location
* It requires password in most cases what is not suitable for execution from cron

### CODE REVIEW

**Comment by MrGeneration** [comment]
Sorry but this change could break existing setups which is why I'm not accepting this change.
By default Zammad package installations do not use password based authentication which is why your approach may work or not.

The backup script you can find in `contrib/` actually can be modified as needed for own uses cases.
We had this discussion on this repository already, if you run your cron as root the issue is not existent. 
Alternatively you could allow whatever user you use for backing up to run that specific command.

**Comment by nijel** [comment]
> Sorry but this change could break existing setups which is why I'm not accepting this change.

The existing code is broken when following the documentation. It creates files owned by `postgres` user which it can not moved by the process running as `zammad` user.

>  By default Zammad package installations do not use password based authentication which is why your approach may work or not.

I did the installation from package and PostgreSQL access is using password.

> The backup script you can find in contrib/ actually can be modified as needed for own uses cases.

Yes, and they will be overwritten on package upgrade, what is really lovely.

> if you run your cron as root the issue is not existent

Why does the [documentation](https://docs.zammad.org/en/latest/appendix/backup-and-restore.html) tell to run it as `zammad` user? Also running arbitrary things as root is not a good security practice. Especially if it can be easily avoided (and the script does that for MySQL).

**Comment by monotek** [comment]
A pr fixing the problem would be really welcome :)

**Comment by MrGeneration** [comment]
I'll be re-thinking this topic.
Please allow me *a lot* time.

Regarding your comments
> Yes, and they will be overwritten on package upgrade, what is really lovely.

That is how a package installation works, not really something we can change. If you change something in existing files it's not update safe. If you want to use contrib files, copy them some where safe...

> I did the installation from package and PostgreSQL access is using password.

Remove your password from `database.yml` and check if Zammad can still start. It should be able to. ;)

> Why does the documentation tell to run it as zammad user? Also running arbitrary things as root is not a good security practice. Especially if it can be easily avoided (and the script does that for MySQL).

Seems like you skipped the second sentence that does link to two issues that are handling these topics.
Any way, I'll be thinking it over. Please don't push this PR.

**Comment by nijel** [comment]
> Remove your password from database.yml and check if Zammad can still start. It should be able to. ;)

It indeed works. In any case, I really see no reason why su to `postgres` user should be used. Anyway my patch works fine even when PostgreSQL password is not set/empty, so it should not break anything.

**Comment by monotek** [comment]
I'd like to approve the change but have no time for testing at the moment.

I'm also can't remember, why i've used the su version in the first place. 
I guess there has been some reason for it.
Git blame did'nt help so far :/

**Comment by MrGeneration** [comment]
I remembered. This will break existing installations - here's the reason:

```
root@zammad:/opt/zammad/contrib/backup# ./zammad_backup.sh

# Zammad backup started - Wed Jan  6 10:26:09 CET 2021!

find: ‘/tmp/zammad_backup/*_zammad_*.gz’: No such file or directory
creating file backup...
creating postgresql backup...
pg_dump: [archiver (db)] connection to database "zammad" failed: FATAL:  role "root" does not exist

# Zammad backuped successfully - Wed Jan  6 10:26:30 CET 2021!

root@zammad:/opt/zammad/contrib/backup# su - zammad
zammad@zammad:~$ /opt/zammad/contrib/backup/zammad_backup.sh

# Zammad backup started - Wed Jan  6 10:26:49 CET 2021!

creating file backup...
creating postgresql backup...

# Zammad backuped successfully - Wed Jan  6 10:27:12 CET 2021!

zammad@zammad:~$
```

There are users using `root` for backing up their Zammad installation.
The suggested changes will break default installation with root-user backup.

Beside of that ... 
Your PR only works because the `zammad` user by default is allowed to use socket connections.

This line is clustered and partly non functional:
 https://github.com/zammad/zammad/pull/3352/files#diff-88844eaa4b6b3f848d8255dc85dbda46c59f389882049277189fb0a2b99c64afR54

**Comment by nijel** [comment]
> This line is clustered and partly non functional:

Indeed, it was missing user parameter, sorry for that.

Anyway the patch certainly could be improved, the question is whether you are interested in this direction.

**Comment by MrGeneration** [comment]
This will take time on my end for fiddling that approach to an end.

**Comment by monotek** [comment]
Why are root users an issue?
In the documentation we advise to use the zammad user: 
https://docs.zammad.org/en/latest/appendix/backup-and-restore.html?highlight=backup

**Comment by MrGeneration** [comment]
> Why are root users an issue?
Because there are users / systems that are using that approach.

> In the documentation we advise to use the zammad user:
We both know how users and documentations work. :-)

Beside of that we also had similar discussions on the following (linked) issues:
* https://github.com/zammad/zammad/issues/2508
* https://github.com/zammad/zammad/issues/2705

Again, I'll have a look at the approach here.
As it needs work it will take time from my end.

**Comment by monotek** [comment]
> Because there are users / systems that are using that approach.

Why should we care for users not following the documentation?
Imho if somebody changes stuff he should also take care of the changed setup completely.

I've tested the change. 
Backup with zammad user and restore with root user works for me.

**Comment by MrGeneration** [comment]
> Backup with zammad user and restore with root user works for me.

Really? Doesn't work on my vanilla installation without any administrative changes:
`pg_dump: [archiver (db)] connection to database "zammad" failed: FATAL:  Peer authentication failed for user "zammad"`

My machine in that case is a Debian Buster minimal installation.
Installation is 1 by 1 followed the Zammad documentation.

---

The reason I do care about those installations that I'm trying to keep impacts as low as possible.
Beside of that the support requests nuke my desk - I'd like to avoid that where I can.

---

Why do we use
```
   PGPASSWORD="${DB_PASS}" pg_dump \
        --dbname "${DB_NAME}" \
        --username "${DB_USER}" \
        --no-privileges --no-owner --clean \
        --compress 6 --file "${BACKUP_DIR}/${TIMESTAMP}_zammad_db.psql.gz"
```

Above approach is not recommended according to postgresql documentation:
http://www.postgresql.org/docs/current/static/libpq-envars.html

A not fully tested (yet) approach could look like the following.
This also ensures we don't receive the next PR within the next days to improve
```
    cat <<EOT >> ~/.pgpass
*:*:${DB_NAME}:${DB_USER}:${DB_PASS}
EOT
    chmod 600 ~/.pgpass
    pg_dump \
        --dbname "${DB_NAME}" \
        --username "${DB_USER}" \
        -h localhost \
        --no-privileges --no-owner --clean \
        --compress 6 --file "${BACKUP_DIR}/${TIMESTAMP}_zammad_db.psql.gz"
    rm ~/.pgpass
```

Above is the fastest and dirties approach I could find.

I did not verify
* that restoration is working
* the dump is what we expect and need

I did verify
* the user running the command does not matter

Possible improvements beside testing (also for docker...)
* also check for the database servers hostname in case it's not localhost


What do you think? ^^

**Comment by MrGeneration** [comment]
Any thoughts on my above suggestion? ^^

**Comment by nijel** [comment]
Changing the user configuration is something that can go easily wrong (what if the file exists, what if it contains wrong credentials for the same service, ...). You better use `PGPASSFILE` with a temporary file for that.

Anyway, passing the password in the environment is safe on Linux, you will not get it with `ps`. I have no clue if Zammad supports running on other systems which might do this.

On the other side, what certainly is not safe is passing it on a command line, and that is what you do with MySQL backups ;-).

**Comment by MrGeneration** [comment]
> Changing the user configuration is something that can go easily wrong (what if the file exists, what if it contains wrong credentials for the same service, ...). You better use PGPASSFILE with a temporary file for that.

I already said: This method is not recommended by postgresql developers.
My suggestion does create a temporary `.pgpass` file to do it the supported way.

I don't see any part where we do change configurations on the instance host directly.
If you mean that we should check for that file before hand, I don't see why we shouldn't.

I may just not get what you want to tell me correctly.

> On the other side, what certainly is not safe is passing it on a command line, and that is what you do with MySQL backups ;-).

Let's please focus on the topic. ;-(

**Comment by nijel** [comment]
> I already said: This method is not recommended by postgresql developers.

Yes, it is not recommended because on some systems the environment can be listed by an unprivileged user. This is not the case on Linux, so the recommendation might not be relevant for Zammad (though I have no clue on what operating systems to you support). Any other solution will be more complex, so you should evaluate whether introducing the complexity is reasonable.

>  My suggestion does create a temporary `.pgpass` file to do it the supported way.

Your code does append to `~/.pgpass` and removes it after the backup. In case the file was existing and was used for some other things it would be gone now.

Something like this would avoid that:

```
export PGPASSFILE=`mktemp`
chmod 600 "$PGPASSFILE"
cat <<EOT >> "$PGPASSFILE"
*:*:${DB_NAME}:${DB_USER}:${DB_PASS}
EOT
pg_dump ....
rm "$PGPASSFILE"
```

**Comment by wucherpfennig** [comment]
Hi guys
we would very much appreciate if you could update the backup script to use the db password if it is available.

Reason: there are other systems who might access a zammad database too (like metabase) and the require passwords...

The initially proposed update from @nijel (ENV Vars) works fine.

BR wucherpfennig

**Comment by mgruner** [comment]
@nijel I tried to consolidate all changes of this and another related PR in #3621. This could be the basis for a merge if there is a consensus. 
Would you be so kind to review the changes there and let me know if they work for you?

**Pull request closed without merging**
