### PR TITLE
Add RocketChat integration

### PR DESCRIPTION
**Pull request by osallou**
This PR adds RocketChat integration, it mimics Slack.
    
It provides browser configuration to request notifications on ticket create/update/etc. Notifications are sent on defined channel. Configured user must have access to this channel.

Additionally, if article contains a user mention with @userid (one or many), a direct message is sent to specified users help with message templates.
By defaults it sends information that user is mentioned in ticket XXX with text of note.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hey @osallou - thanks for this great pull request 😍 Unfortunately currently we don't have the resources to wether review nor maintain this feature. However, we'd be happy to support you on making this the first Zammad extension 👍

**Comment by osallou** [comment]
@thorsteneckel , what are zammad extensions? What should I do for this?

**Comment by MrGeneration** [comment]
Hey,

sorry for the wait!
We currently have not too much documentation on this, however, the following community post might help you fiddling around (as you already have the code, this should help you):

https://community.zammad.org/t/examples-of-zpm-files/2881/3?u=mrgeneration

**Comment by osallou** [comment]
Thanks. I had look and am trying to create one. However there are constraints... For db seeds you need to manually run rake commands, and for coffee scripts you also need to regenerate assets in rails server and restart server and scheduler for transactions.
So uploading a package is not enough for admin, manual steps and restarts are needed.

**Comment by pawu11** [comment]
Or Microsoft Teams ;-)

**Comment by osallou** [comment]
I created a first extension at https://github.com/genouest/zammad-rocketchat
Needs more testing I think but looks good.

I added along package the instructions to regenerate assets etc. to get it up

**Comment by thorsteneckel** [comment]
Hey there! It's been a while. I was reviewing this PR and talked to my colleagues about it. While doing so we found out that Zammad is actually perfectly capable of integrating RocketChat without any changes needed via the Slack integration. This comes from the fact that [RocketChat is API compatible](https://github.com/RocketChat/Rocket.Chat/issues/202) with Slack. However, this isn't very clear in the Zammad UI. Therefore we will enhance the text on the integration view (in Zammad), the documentation and our new feature browser over at https://zammad.com.
However, I'll close this PR now. Thanks for filling the gap @osallou !

**Comment by osallou** [comment]
Just adding comment, though slack integration can be done to be notified of new/updated tickets, it does not provide user notification via "@xxx msg" in tickets.
The rocketchat plugin provided supports that.

**Pull request closed without merging**
