### PR TITLE
Feature: Add support to webhook trigger

### PR DESCRIPTION
**Pull request by dukex**
I started to make the webhook feature. I'm using the trigger behaviour as described in @thorsteneckel document, any comment about it will help me.

This feature will make possible to me create a zammad enricher with external data, or even a conventional bot to my zammad server.

Related with #290

### CODE REVIEW

**Comment by dukex** [comment]
Hi @martini and @thorsteneckel can you give some guidance about my implementation? It`s good enough?

**Comment by thorsteneckel** [comment]
Hey @dukex ! Sorry for the delay. We're pretty busy with the upcoming Zammad 3.5 release (tomorrow). However, it's great to see a contribution for this rather big feature.

TBH I haven't had the required time to have a look in detail. However, the overall style and implementation looks good. We follow the philosophy make it work, make it right make it fast. So let's make it work first and then give it the finishing touch when everything is there.
It's been a while since we (internally) talken about the Webhooks functionality. However, I checked our requirements/specification document. Unfortunately it's in German so I had to translate it. You can find it attached. It should give you a good overview. Let me know your thoughts and questions. 

[Webhooks.zip](https://github.com/zammad/zammad/files/5254143/Webhooks.zip)

**Comment by dukex** [comment]
@thorsteneckel Sorry the delay, now I believe is as specified in the requirements document. I remove the custom webhook models/table, and now I'm using the trigger behavior to call the endpoint.

please let me know if there is anything to be improved!

**Comment by dukex** [comment]
I'll make the tests green ASAP

**Comment by thorsteneckel** [comment]
@dukex sorry for the delay. This looks fantastic 😍 Really great job 👏  There are some rough edges that I'd like to flatten out. Nothing big. Would you prefer an in detail review (probably tomorrow) or should we handle it and take over from here? I plan to release this with the upcoming version 3.6 🤔 You can be damn sure to find your name in the release notes (if you're ok with it) 🔈

**Comment by dukex** [comment]
What is better for you? I don't worry about you handle it, for me, the important is to make this feature a real thing.

**Comment by thorsteneckel** [comment]
Ok then we will take over. I think it's more efficient for the both of us. Please let us know if you plan to perform any changes from now on to avoid additional sync-work. Unfortunately I have to transfer it to our internal GitLab instance to run the complete test suite. This means the next steps will take place "behind the curtain". I'll keep you updated about our progress. Happy hacking!

**Comment by dukex** [comment]
Nice! I'll not update this branch anymore you can move on

**Comment by rosscdh** [comment]
good looking feature +1

**Comment by thorsteneckel** [comment]
Hey @dukex - thanks again for your contribution. I applied some changes as discussed earlier. We will release it with the upcoming version 3.6 🚀

**Comment by MrGeneration** [comment]
Greetings! 👋

I'm currently working on the documentation and would like to know if I would have forgotten anything super important from your perspective? If not, we're good. 😏 

https://github.com/zammad/zammad-admin-documentation/blob/mh/introduce/webhooks/manage/trigger/webhooks.rst

**Comment by dukex** [comment]
@MrGeneration seems great!

**Pull request closed without merging**
