### PR TITLE
Show customer and agent tickets respectively when creating new ticket…

### LINKED ISSUE #1354: Create Ticket Button not intuitive
### Infos:

* Used Zammad version: 1.6.1
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:
The label of the new ticket buttons should distinguish.
Right now both a labled identical
* 

### Actual behavior:
Zammad is used for different groups in the company.
i.e. IT-helpdesk and Human ressources.
All users are member of the ldap group "all_users" and that group is associated with the role "customer".
The users that are responsible for IT-helpdesk are also member of the ldap group "zammd-it-helpdesk" which is associated to the role "IT-Helpdesk agent".

If these it-helpdesk agents press the "+" button to create a new ticket, they get two buttons called "new ticket".
One button links to  the URL: 
http://zammad/#ticket/create
The other button links to the URL:
http://zammad/#customer_ticket_new

It would be useful to have different names for the buttons.

* 

### Steps to reproduce the behavior:
clipboard02

*

### PR DESCRIPTION
**Pull request by muhammadn**
…. Fixes #1354

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @muhammadn ! Great! Thanks for creating this pull request. I think it's one step in the right direction but not the right solution. It doesn't fit for regular agents/tickets that are only in one role. In this case it's to much information and loses the simple elegance.

The behavior should be:

- Agent: `Create Ticket`
- Customer: `Create Ticket`
- Agent + Customer: `Create agent Ticket` and `Create customer Ticket`

Currently I can't see a straight way of doing this since the check for a certain permission is [locked in the frontend ApplicationController](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_application_controller.coffee#L239) which is not accessible from the outer scope.

I would recommend to extract this somewhere into the `App.` scope so it can be accessed. 
ApplicationController should then tunnel calls to this extracted method. What do you think @martini ?

**Comment by muhammadn** [comment]
I think your idea is the way to go and i have to pick up Spine client-side MVC (i came from AngularJS/React and spine is totally new thing)

But i get what you mean. Currently the code runs in App.Controller and i have to extract   `permissionCheck: (key) -> ....` into `App.` so it somehow become in another word, "global" to be accessed from anywhere.

**Comment by thorsteneckel** [comment]
Sorry for the late response. There should be a method called `permitted` on the [Permission model](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/models/permission.coffee). You can define it like [e.g. App.Group.accesses()](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/models/group.coffee#L39).

The content should be the same like in [permissionCheck](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_application_controller.coffee#L239). Actually `permissionCheck` should then call `App.Permission.permitted` internally.

If there are any questions feel free to ask. I am very happy about your support! 🚀

**Comment by thorsteneckel** [comment]
Hi @muhammadn - are there any updates on this?

**Comment by muhammadn** [comment]
Was busy lately with my day job. Sorry about that. I think i will close this first to work on it, don't want to pile up the pull requests, will re-open when i get to the result.

**Comment by thorsteneckel** [comment]
As stated in #1354 this is currently no use case. Closing now.

**Pull request closed without merging**
