### PR TITLE
Remove rsync from docker files

### PR DESCRIPTION
**Pull request by monotek**
* get rid of /tmp/zammad and rsync to /opt/zammad in the docker container
  * migration of stuff from the filesystem should not be needed anymore as all data goes to postgres already

### CODE REVIEW

**Comment by dominikklein** [comment]
@mgruner something for you?

**Review by mgruner — APPROVED** [review]

**Comment by mgruner** [comment]
@dominikklein I would suggest that @fliebe92 and @monotek handle this together when @monotek is back from vacation. There may be other related tasks such as backports to pre-release, stable and also changes in the zammad-docker-compose files.

**Comment by monotek** [comment]
Imho this can be merged for develop now.
Should be cherry picked for stable when 6.0 comes out.
Helm chart and docker compose have to be changed afterwards.

**Comment by fliebe92** [comment]
Merged to `develop` with https://github.com/zammad/zammad/commit/19c60c68665f4b2453879e00717ccf52fc01f3f1.

**Pull request closed without merging**
