### PR TITLE
Prevent assigning conflicting user roles with LDAP sync and nested groups

### PR DESCRIPTION
**Pull request by Kquinn**
PR to fix issue #2540

The issue:
Microsoft Active Directory LDAP implementations utilize nested groups for security and email distribution. As such, users are typically members of multiple groups. When these multiple groups are assigned to different Zammad roles which conflict, the import will simply fail for that user and continue on, resulting in unexpected outcomes in the synchronization.

What this patch does:
Add one method (resolve_role_conflicts) which can detect and resolve these error conditions by granting the user the highest role(s) that do not cause a conflict.  This means if a user is synchronized with groups assigning them both the Agent and Customer roles, the Customer role will be removed and the Agent role will remain. If a user is synchronized with groups assigning the Administrator, Agent, and Customer roles, the Customer role is removed and both Administrator and Agent remain.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Wow @Kquinn - thanks a ton for your contribution! I will have to do some tests with this but it looks really elegant and promising. There will be a release in the next week(s) and I won't be able to do so before that. However, reviewing open PRs is one of my top priorities after the the release.

**Comment by Kquinn** [comment]
@thorsteneckel thank you for the feedback and expected timeline for review.

This code solves my use-case and prevents the issue mentioned in #2540, where no custom roles are created/used, but could still lead to unexpected results when custom roles are used and the values of least to most privilege do not correspond with the role IDs.

One possibility for making this universal would be to allow the user to define an "order" or "rank" that would be used to determine which role should supersede the other.

**Comment by martini** [comment]
closed by accident - re-open

**Comment by thorsteneckel** [comment]
Hey @Kquinn - it's been a while now. Please excuse the delay. We decided to resolve #967 so that there are no Role conflicts and Agents can be Customers at the same time (and vice versa). This means that there is now no Role conflict to resolve any longer and you can actually sync your LDAP Roles to Zammad without any change needed. This is possible since Zammad 3.5 (previous version, 3.6 is currently latest). Therefore I'll close this PR. Anyhow, thanks to your contribution.
You had to make some sacrifices regarding preference/priority but over all I really liked your code and approach. Let us know if you'd like to work full time on Zammads code base 😅 Anyhow, thanks again! Closing now.

**Pull request closed without merging**
