### PR TITLE
fixes #1706, add integer and tree_select types to Triggers Management(New Trigger)…

### LINKED ISSUE #1706: Trigger - missing integer and tree_select as 'Conditions for effected objects'
### Infos:

* Used Zammad version: 2.1.x
* Installation method (source, package, ..): yum
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.2.23
* Elasticsearch version: -
* Browser + version: Firefox ESR 52.5.2

### Expected behavior:

* Have 'integer' and 'tree_select' objects in the list of the 'Conditions for effected objects'.

### Actual behavior:

* Both are missing in 'Conditions for effected objects', but exist as valid selection for the 'Execute changes on objects'.

### Steps to reproduce the behavior:

* Create a ticket object of the type 'integer' or 'tree_select'
* Go to 'Triggers'
* Create a new one and try to select your created field as a condition

missingtriggerconditions

Yes I'm sure this is a bug and no feature request or a general question:

* I couldn't find a list with valid 'Conditions for effected objects' in the diverse documentations

### PR DESCRIPTION
**Pull request by umarsheikh**
… form under conditions for effected objects

### CODE REVIEW

**Comment by umarsheikh** [comment]
This commit fixes the issue. Please review and merge :)

**Comment by thorsteneckel** [comment]
Hi @muhammadn - please review and check if the changes work as expected. Thanks!

**Comment by muhammadn** [comment]
@umarsheikh Thanks! Looks good to me, will merge. 🚀

Fixes #1706

**Comment by umarsheikh** [comment]
thanks @muhammadn !

**Pull request merged**
