### PR TITLE
Fixed #2079 by filtering out inactive users

### LINKED ISSUE #2079: Inactive users show up within autocomplete of the CC field
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): source
* Operating system: linux, ubuntu 18.04
* Database + version: mysql-5.7.22
* Elasticsearch version: 5.6.8
* Browser + version: chrome 67
* Please drop me a note in case you need the log file...

### Expected behavior:

* When starting to type within the CC field, autocomplete only active users

### Actual behavior:

* When starting to type within the CC field, inactive users show up within the autocomplete list

### Steps to reproduce the behavior:

* Create a user
* Mark the user "active: no"
* Create a new email ticket (bottom left: +, top right: email)
* Start typing the user's name within the CC field and watch the autocomplete show up

Yes I'm sure this is a bug and no feature request or a general question.

### PR DESCRIPTION
**Pull request by uli-heller**
Probably a poor fix, but it works for me ;)

```
uli@ulinuc:~/git/forked/zammad$ rubocop
rubocop: Befehl nicht gefunden.
uli@ulinuc:~/git/forked/zammad$ coffelint
coffelint: Befehl nicht gefunden.
```

### CODE REVIEW

**Comment by martini** [comment]
Hi @uli-heller 

thanks for the PR. There is one more (UX) issue coming up. Maybe you have an idea how to deal with that.

Use case:
1) I want to create a ticket form an calling customer.
2) The customer is not appearing in the search field.
3) No I want to create the user, but unfortunately Zammad does not allow me that, a error appears - a user with this email address already exists.

What Ideas do you have to solve this UX problem?

 -Martin

**Comment by thorsteneckel** [comment]
Related to #2015

**Comment by uli-heller** [comment]
Hi Martin,

thanks for the remark. Now I see the connection between my issue and the 
other issue...

Without my PR, the customer shows up within the search field, right?
You can probably select this customer and you're fine.

But on the other hand:
Shouldn't an inactive customer be prevented from creating tickets? The 
customer might be a spammer :(

Maybe the topic is too huge. Can we close the pull request? I'll keep
me patch private and apply it to my local instance only since it fits to
my requirements quite well.

Thanks a lot & best regards, Uli



Am 15.06.2018 um 10:14 schrieb Martin Edenhofer:

**Comment by SummerStorm** [comment]
@martini 
>Use case:
>   1. I want to create a ticket form an calling customer.
>   2. The customer is not appearing in the search field.
>   3. No I want to create the user, but unfortunately Zammad does not allow me that, a error appears - a user with this email address already exists.
>
>What Ideas do you have to solve this UX problem?
 
Here's my rough proposal: we display the inactive users with struck-out names and crossed-out icons. Possibly under a divider that reads "Inactive Users". Theses inactive users would of course be unselectable.

proposal

Basically only changing the frontend Javascript code to fix how inactive user/organizations are presented, while making no backend changes.

**Comment by martini** [comment]
@mrflix Can you have a look on the proposal of @SummerStorm ?

**Comment by thorsteneckel** [comment]
@SummerStorm - this should be resolved by the changes you and @mrflix made – right? If so: Please close this PR and refer to the commit. Thanks!

**Comment by SummerStorm** [comment]
This has been fixed by f4c50ae0fa23faa6ed4e461e2fc5202961b34598.

**Pull request closed without merging**
