### PR TITLE
Wrong translation on Turkish

### PR DESCRIPTION
**Pull request by mandev0**
This translation was false. Someone added a hospital name to the footer. The part was "IKCU Atatürk Eğitim Ve Araştırma Hastanesi". This is the correct translation.

### CODE REVIEW

**Comment by MrGeneration** [comment]
@mgruner how to we proceed with direct translation file PRs that do not come via weblate?
In this scenario, at least per translation list, the translator credit gets lost with the current state of this PR.

**Comment by mgruner** [comment]
@MrGeneration there are two options. Either we do the transfer work, or we reject all PRs about this and ask people to get an account in Weblate.
I would recommend the latter. We can also place a README file that exaplains this in the i18n/zammad folder.

**Comment by MrGeneration** [comment]
I can't decide that.
If we'd transfer it via File import you can also provide a Name and email address, that automatically creates an account and would require consent.

**Comment by mgruner** [comment]
Hi @mandev0. Thank you so much for spotting this and suggesting a fix. May I encourage you to get an account on [translations.zammad.com](https://translations.zammad.com) and making the required changes there?
To clarify this new process (we just introduced gettext / Weblate a few days ago), I also added a `README.md` file to the `i18n` folder. Sorry for the trouble.

**Pull request closed without merging**
