### PR TITLE
fixed #1387

### LINKED ISSUE #1387: number wrap in report page
Like:

image

fix: add `white-space:nowrap` to css style.

### PR DESCRIPTION
**Pull request by NeverMin**
fixed in my production server, work fine.

### CODE REVIEW

**Comment by NeverMin** [comment]
Hi @thorsteneckel , Do I need re-config my **Sublime**?

**Comment by thorsteneckel** [comment]
Hi @NeverMin - yes, seems like your Sublime strips the trailing whitespaces. Should be sufficient to turn it off just in cases where the whitespaces are needed or like this one (third party).

@mrflix will review your PR and issue.

**Comment by thorsteneckel** [comment]
Hi @mrflix - could you please have a look at this?

**Comment by thorsteneckel** [comment]
Merged! Thanks a lot guys 🥇

**Pull request merged**
