### PR TITLE
support rocket chat integration, issue #878

### PR DESCRIPTION
**Pull request by NeverMin**

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @NeverMin - sorry for the delay. Sweet PR! From my first impression this looks like a lot of duplicate code. Mostly variations of the Slack integration. Am I right?

**Comment by NeverMin** [comment]
Thank you for your time and review, you are right, I refer to the Slack code and use this [gem](https://github.com/thiagofelix/rocket-chat-notifier), let me know if you have any questions!

**Comment by MrGeneration** [comment]
Just talked to Gabriel from rocket.chat 😍 

He's very interested in bringing this forward and would love to assist us when we have trouble. :-)
He also mentioned that rocket.chat is very close to Slack so this might be quite easy to do.

This also explains all the duplicate from Nevermind👍

**Comment by NeverMin** [comment]
@MrGeneration , OK, I will fix it base on 2.9.0 and unit test.

**Comment by NoxInmortus** [comment]
Hello, is this pull request still actuality ?

**Comment by MrGeneration** [comment]
Hey Never,

do you have an update? Do you need any help from our site? :)

**Comment by NeverMin** [comment]
Hey @NoxInmortus and @MrGeneration , I am very sorry for the delay, I will process this PR as soon as next week.

**Comment by NoxInmortus** [comment]
Thanks for the reply, glad to read that : )

**Pull request closed without merging**
