### PR TITLE
Fixed issue #2010 by filtering out inactive organizations on the backend

### PR DESCRIPTION
**Pull request by SummerStorm**
This fixes issue #2010 by filtering out inactive organizations on the backend.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @SummerStorm. Thanks for creating a pull request for this! For performance reasons we should filter the active flag in the DB / SearchIndexBackend (Elasticsearch) instead of Ruby. Could you please change your code accordingly?

**Comment by SummerStorm** [comment]
Sure, no problem. I will get right on it.

**Comment by thorsteneckel** [comment]
@SummerStorm - this should be resolved by the changes you and @mrflix made – right? If so: Please close this PR and refer to the commit. Thanks!

**Comment by SummerStorm** [comment]
This has been fixed by 3186d5e4d763f8e367f8cf9d5c4eae918284bdbf.

**Pull request closed without merging**
