### PR TITLE
added russian translations to mail notifications

### PR DESCRIPTION
**Pull request by ruslanjan**
I needed them myself and thought it would be nice to contribute to the project. 

My mother tongue is Russian so it should be correct. better then nothing anyway

### CODE REVIEW

**Comment by ruslanjan** [comment]
I think I translated everything. You can review now :)

**Comment by ruslanjan** [comment]
@thorsteneckel can you add `hacktoberfest-accepted` label to the PR or add the `hacktoberfest` topic to the repository to opt-in the whole repository. Not insisting but would be glad if  you add :).

**Comment by mgruner** [comment]
@mantas could you check and apply this perhaps?

**Comment by mantas** [comment]
Hi @ruslanjan 

Thank you for you contribution. This PR is now merged with above commit. It will be included in coming up release.

**Pull request closed without merging**
