### PR TITLE
Add support for Signal as a channel

### LINKED ISSUE #804: implement support for Signal
Hey, I have seen you have delivered support for Telegram in the last release. Would be cool, if there was support for Signal, which is a more secure messenger.

### PR DESCRIPTION
**Pull request by abeluck**
Here is an implementation of Signal to be used as a channel in Zammad. Fixes #804

It does not use Signal's API servers directly, instead, the Signal specific code (encryption, key handling, registration, etc) is handled via a bridge service created specifically for this project: [Sigarillo](https://gitlab.com/digiresilience/link/sigarillo/).

[Sigarillo](https://gitlab.com/digiresilience/link/sigarillo/) is a simple node.js application that provides a few basic HTTP endpoints for registering and verifying a Signal number. It also provides two endpoints for sending and receiving messages. It uses Postgres to store state (account keys, session keys, and so on). Messages are only fetched when the receive endpoint is called, and are not persisted to disk. Under the hood Sigarillo uses the same javascript library as the signal desktop application. Sigarillo is straightforward to host and also comes with a docker image to easily get up and running.

**Why Sigarillo?** Why not just implement Signal directly into Zammad? Because there are no Signal libraries available for Ruby. Implementing the [Signal specifications](https://signal.org/docs/) (double ratchet, x3dh, sesame, et al) would take an incredibly significant amount of effort. Hence, the decision to use existing, vetted libraries to build Sigarillo.

This makes the implementation in Zammad very simple (as you can see in this PR). Assuming a user has a Sigarillo instance available, and a number registered and verified, to add the channel to Zammad a user simply must provide the Sigarillo URI for the number and the secret API token (provided by Sigarillo).

We've been using this channel in several production deployments since November, and it is working great.

Circle CI Builds: https://circleci.com/gh/digiresilience/zammad

### CODE REVIEW

**Comment by martini** [comment]
closed by accident - re-open

**Comment by NoxInmortus** [comment]
Hello,

Is this planned to be merged ?

**Comment by MrGeneration** [comment]
Sorry, but we can't provide any feedback on this as of now.
Please do not bump pull requests as this creates distractions on this repository.

As soon as anything moves into any directions on this pull request, we'll update it accordingly. 💪

**Comment by abeluck** [comment]
Hi folks.

Due to lack of pickup by Zammad we're closing this PR. 

We've re-implemented the Signal channel as a package you can install via the Admin > Packages UI. 

The project lives over here:  https://gitlab.com/digiresilience/link/zammad-addon-sigarillo

We also have a package that adds a **WhatsApp**  channel: https://gitlab.com/digiresilience/link/zammad-addon-quepasa

For questions and community support please do not contact Zammad. Instead join us on our dev mailing list here: https://lists.mayfirst.org/mailman/listinfo/guardian-dev

**Pull request closed without merging**
