### PR TITLE
Listen to both IPv4 and IPv6 #3371

### PR DESCRIPTION
**Pull request by maxxer**

### CODE REVIEW

**Comment by thorsteneckel** [comment]
@mantas would you mind having a look?

**Comment by mantas** [comment]
Hi @maxxer 

Thank you for your contribution! Your changes are now merged with the following commit https://github.com/zammad/zammad/commit/062f19df3c227441e72ea548fcce294ebbf2211a

**Comment by monotek** [comment]
This breaks our compose container :(

```
zammad-nginx_1          | starting nginx...
zammad-nginx_1          | nginx: [emerg] a duplicate listen 0.0.0.0:8080 in /etc/nginx/sites-enabled/default:15
```

@maxxer 

Maybe this works for ipv4 and ipv6.

```
listen [::]:80 ipv6only=off;
```

I'm a bit bussy at the moment.
Could you try that out?

**Comment by MrGeneration** [comment]
The reason for this issue lays within the docker-entry point of nginx:
https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/10-listen-on-ipv6-by-default.sh#L24

I personally believe that vHost files shouldn't contain listen directives at all for default ports. 
A workaround would to provide the IPv6 option commented out to help admins but ensure functionality on existing systems.

As it's already merged I believe this requires a regression issue.

**Comment by maxxer** [comment]
> The reason for this issue lays within the docker-entry point of nginx:
> https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/10-listen-on-ipv6-by-default.sh#L24

The `grep` contain two spaces, maybe that's why it's failing?

> I personally believe that vHost files shouldn't contain listen directives at all for default ports.
> A workaround would to provide the IPv6 option commented out to help admins but ensure functionality on existing systems.

Indeed, one has to always edit the file for `server_name` at least.

> As it's already merged I believe this requires a regression issue.

Apologies for the trouble

**Comment by monotek** [comment]
We don't use the nginx docker container.
We're installing nginx in a debian container.

Imho `listen [::]:80 ipv6only=off;` should work for ipv4 and ipv6 in a single line but the sed in the docker entrypoint would still fail.
Added a comment to @MrGeneration pr, which should fix it for any version: https://github.com/zammad/zammad-docker-compose/pull/207#discussion_r619641298

Closing this pr again.

**Pull request closed without merging**
