### PR TITLE
feature: fix #3380, now category display how many deep answers contains

### LINKED ISSUE #3380: Counter for KB answers
### Infos:

* Used Zammad version: 3.0 and onward
* T#1082873 

### Expected behavior:

* Knowledge Base entries should display a counter indicating how many answers each category and their subcategory contains.
* In each category, regardless of main or subcategory, this indicator should be displayed.

### Actual behavior:

* There is no indicator of how many answers each category contains.

This is feature request

### PR DESCRIPTION
**Pull request by FiloSpaTeam**

### CODE REVIEW

**Comment by mantas** [comment]
Hi @FiloSpaTeam 

Could you post a screenshot how it looks after the change?

**Comment by FiloSpaTeam** [comment]
Schermata da 2021-07-15 11-56-07

Alternative:
Schermata da 2021-07-15 11-58-38

With:
```css
hr {
width: 90%;
border: 0;
border-top: 1px solid #eee;
}
```

**Comment by MrGeneration** [comment]
Personally like the `hr` approach to give some feedback. :)

**Comment by mantas** [comment]
@mrflix what do you think?

**Comment by FiloSpaTeam** [comment]
So i should fix the pull request with `hr`?

**Comment by mantas** [comment]
Let's wait for response from @mrflix who is overlooking UI :)

**Comment by mrflix** [comment]
I don't like that the amount has the same visual hierarchy level as the title. The title is way more important. So that amount should be smaller, lighter or both. The horizontal divider looks good.

**Comment by FiloSpaTeam** [comment]
Schermata da 2021-07-19 18-52-17

This applying a class `small` on `span`

Schermata da 2021-07-19 18-53-41

This with `font-weight: 300`

**Comment by mrflix** [comment]
Lighter → I meant in terms of color. I'd gray it out a bit.
Maybe we just gray it out and don't use the `<hr>` to make it look like the tiles on the dashboard:

Screenshot 2021-07-19 at 18 56 46

**Comment by FiloSpaTeam** [comment]
Ok understood

**Comment by FiloSpaTeam** [comment]
Schermata da 2021-07-19 19-06-48

This applying `stat-label` and `stat-detail` classes

**Comment by mrflix** [comment]
Looks good!
I'm not sure if we should reuse the classes here. I'd rather go with creating own classes for this case and set the colors (title #444a4f, detail #b4b7b9) there:

Screenshot 2021-07-20 at 10 32 09

Screenshot 2021-07-20 at 10 33 34

**Comment by mantas** [comment]
What do you guys think about adopting this for public KB UI?

**Comment by mrflix** [comment]
How would this help a user? If I look at the knowledge bases of big players, none of them has a "number of answers" indicator on their top level: 

[Google](https://support.google.com/)
Screenshot 2021-07-23 at 08 30 51

[Facebook](https://www.facebook.com/help)
Screenshot 2021-07-23 at 08 31 33

[Apple](https://support.apple.com/)
Screenshot 2021-07-23 at 08 31 11

**Comment by MrGeneration** [comment]
This has been requested by a fairly big customer. 
However, we've seen this kind of request in the past as well.

Does it help the end user? I don't know.

**Comment by mantas** [comment]
If I was making the decision, I'd make this an opt-in setting. Personally I don't like showing the count, but there's enough noise to give people what they're asking for :)

**Comment by mrflix** [comment]
> This has been requested by a fairly big customer.

Did the customer ask for the answer count in the public KB or the internal KB?

**Comment by MrGeneration** [comment]
Sorry for the wait, thank you for your patience!

We've came to point that this would be useful to show internal for agents.
On public interface there should be a knowledge base admin setting (which defaults to off) that allows administrators to enable the answer counter on public pages.

We feel that a counter on public pages may be too technical for most of our user base but also feel that it could come in handy for others.

**Comment by FiloSpaTeam** [comment]
Don't worry, so i need to add a simple check input (default to off) to enable/ disable the feature, right?

**Comment by MrGeneration** [comment]
Yes, you're looking for Settings on this regard.
@mantas should be able to give you pointers in case you're getting lost. 🙏

**Comment by FiloSpaTeam** [comment]
I'll take some times in the next weeks :)

**Comment by dominikklein** [comment]
@FiloSpaTeam do you think that you can work on this the next time, otherwise we can maybe try to add the missing things on our side.

**Comment by FiloSpaTeam** [comment]
I'll schedule it for the 21/03, sorry for my delay. I had some troubles with other sources

**Comment by FiloSpaTeam** [comment]
> @FiloSpaTeam do you think that you can work on this the next time, otherwise we can maybe try to add the missing things on our side.

What i did today:
- created a migration for the dedicated column inside the table knowledge_bases
- create a new tab under knowledge settings
- add checkbox using the js deidcated for custom input

What i need to understand is: how can i access in JS, the knowledge base active object?

**Comment by mantas** [comment]
Hi @FiloSpaTeam 

Where are you trying to access the active KB object?

**Comment by FiloSpaTeam** [comment]
Inside here:

app/assets/javascripts/app/views/knowledge_base/_reader_list_item.jst.eco

**Comment by mantas** [comment]
See bottom of reader_list_item.coffee ;)

**Comment by FiloSpaTeam** [comment]
> See bottom of reader_list_item.coffee ;)

i found a way, thanks for the suggestion. The code is up :)

I needed to fix the checkbox jst.eco too because when you submit a checkbox unchecked, the checkbox is not submited in any way (this is not a bug essentially but a HTML feature), so i added an hidden input with a false value, the value will be replaced by the checkbox automatically if checked :)

**Comment by mgruner** [comment]
Closed via 74ee3b91.

**Pull request closed without merging**
