### PR TITLE
Feat/hooks

### PR DESCRIPTION
**Pull request by ma-jahn**
From time to time it's required to interact with or react to status updates within the zammad chat application.

The aim of this Pull Request is to add certain hooks to the application, so the initiator can handle events like `onReady` or `onCloseTransitionend`.

Here a full list of hooks:

- onReady
- onCloseAnimationEnd
- onError
- onOpenAnimationEnd
- onConnectionReestablished
- onSessionClosed
- onConnectionEstablished
- onCssLoaded

```
this.chat = new ZammadChat({
  chatId: 2,
  host: host,
  cssUrl: cssUrl,
  debug: true,
  background: '#494d52',
  flat: true,
  idleTimeout: 1,
  idleTimeoutIntervallCheck: 0.5,
  inactiveTimeout: 2,
  inactiveTimeoutIntervallCheck: 0.5,
  waitingListTimeout: 1.2,
  waitingListTimeoutIntervallCheck: 0.5,
  onReady(data) {
    console.warn('onReady', data)
  },
  onCloseAnimationEnd(data) {
    console.warn('onCloseAnimationEnd', data)
  },
  onError(data) {
    console.warn('onError', data)
  },
  onOpenAnimationEnd(data) {
    console.warn('onOpenAnimationEnd', data)
  },
  onConnectionReestablished(data) {
    console.warn('onConnectionReestablished', data)
  },
  onSessionClosed(data) {
    console.warn('onSessionClosed', data)
  },
  onConnectionEstablished(data) {
    console.warn('onConnectionEstablished', data)
  },
  onCssLoaded(data) {
    console.warn('onCssLoaded', data)
  }
})
```

Due to an Error on my end this PR also contains the fix for #2882.

### CODE REVIEW

**Comment by ma-jahn** [comment]
Thank you for merging #2882 !
I've merge your latest develop branch into my PR and run `gulp no-jquery` to re-build the JS files.

Also i want to point out that i've picked the callback names based on their surrounding function names.
Since jQuery is using `.animate` the function is called `onOpenAnimationEnd` resulting in a hook `onOpenAnimationEnd`.
The no-jquery version is listening for 'transitionend', resulting in a hook `onOpenTransitionend`.

To have clean code, i'd like to rename the functions, so we have identical callbacks in `chat.js` and `chat-no-jquery.js`.

**Comment by thorsteneckel** [comment]
Cool! Looking forward for the consistent naming. Just let me know when you're ready 👍

**Comment by ma-jahn** [comment]
@thorsteneckel done! From my understanding chat.coffee is the main implementation and therefore i've changed the transitionend callback to AnimationEnd.

**Comment by thorsteneckel** [comment]
Hey @ma-jahn - thanks for the follow up! Seems like something went wrong when merging latest develop. This PR undos some of the recent changes made to other files. Would you mind resolving this before we can proceed?

**Comment by ma-jahn** [comment]
Closed in favour of #2888.

**Pull request closed without merging**
