### PR TITLE
Do not fail Zendesk import if subject is not set

### PR DESCRIPTION
**Pull request by luqasn**
Fall back to description or hard-coded title "No title" instead if ticket has no subject in Zendesk (which is allowed).

### CODE REVIEW

**Comment by luqasn** [comment]
Should probably add a test for this, but I think you need to create a title without a title in your zendesk testing account. Not sure if that is possible via the normal UI, we created these tickets without subject via the API.

**Comment by luqasn** [comment]
Not sure if you want the hard-coded english string "No title" there, but I figured an ugly last resort is better than an import failing completely, especially because you have to wipe your database in order to start over.

**Comment by thorsteneckel** [comment]
Hi @luqasn - Nice! I'll have a look at it this week.

**Comment by thorsteneckel** [comment]
Hi @luqasn - Thanks! I merged your commit and changed the default title to a `-` as Zammad usually does.

**Pull request closed without merging**
