### PR TITLE
Fix mysql issue on boolean type

### PR DESCRIPTION
**Pull request by kapilchoudhary**
I have fixed the error coming when try to add new attribute of type boolean and assign default value to the object.

### CODE REVIEW

**Comment by monotek** [comment]
Is this a fix for: https://github.com/zammad/zammad/issues/1658 ?

**Comment by thorsteneckel** [comment]
@muhammadn - I think is the right fit for you as our ObjectManager Attribute expert 🤓

**Comment by muhammadn** [comment]
@kapilchoudhary is this problem with the frontend not having the `default` value selected when adding a new boolean object in object manager?

**Comment by muhammadn** [comment]
duplicate of #1617

**Comment by muhammadn** [comment]
Fixed this bug in https://github.com/zammad/zammad/commit/97a9991609aa6a8a713bdc62b6dac8ce8fa93e4e

Closing for now

**Pull request closed without merging**
