### PR TITLE
Support HTML5 'required' attribute in forms

### PR DESCRIPTION
**Pull request by xf-**

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @xf- We're sorry for the extreme delay. I'd love to merge it but can you please add tests first? We're happy to support you on that. Thanks!

**Comment by xf-** [comment]
really busy - didn't forget

**Comment by thorsteneckel** [comment]
Hi @xf- - I discussed this with @mrflix a while ago and we came to the conclusion that there is already a test that needs to get extended. We've just switched our browser testing framework/workflow and will integrate your changes when we change the existing test.

**Comment by martini** [comment]
closed by accident - re-open

**Comment by mantas** [comment]
Hi @xf- 

disregard the message, I was looking at a wrong file, all is good 

~~Sorry for the long wait. Looks like the PR is just a test extension. Did the rest of PR got lost over time? What was the original intention?~~

**Comment by mgruner** [comment]
@xf- this was now finally merged. Sorry for the long delay. The details took much more time than expected.
Thank you so much for your contribution!

**Pull request closed without merging**
