### PR TITLE
cast 'true' to true and 'false' to false in case of boolean column ad…

### LINKED ISSUE #1613: Adding attribute to object with Boolean type and default value gives SQL error
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: source
* Operating system: Ubuntu
* Browser + version: Chromium
* DB: MySQL

### Expected behavior:

* Create a new attribute in object with default boolean value

### Actual behavior:

* 
Production.log:

Mysql2::Error: Invalid default value for 'new_column': ALTER TABLE `tickets` ADD `new_column` tinyint(1) DEFAULT 'false' (ActiveRecord::StatementInvalid)
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'

### Steps to reproduce the behavior:

* 
Admin -> Objects -> New attribute -> Format as Boolean, display yes/no, default false

### PR DESCRIPTION
**Pull request by umarsheikh**
…dition, fixes #1613

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @umarsheikh - nice! Would you mind creating a test for this?

**Comment by umarsheikh** [comment]
sure @thorsteneckel I will write tests for it soon! (will try to finish it today or tomorrow latest!)

**Comment by thorsteneckel** [comment]
Great 🚀 Feel free to ask questions if they arise.  Thanks for your support.

**Comment by umarsheikh** [comment]
the decrease in coverage looks inconsequential, since the commit only adds tests and ends up reducing coverage. (May be it is because the first commit on this PR failed.) In any case, the coverage should increase with more tests, not decrease, so this report of decreasing coverage can be safely ignored.

**Comment by thorsteneckel** [comment]
Great! I'll have a look at the next free slot.

**Comment by umarsheikh** [comment]
Hello @thorsteneckel any update on reviewing and mergine this PR?

**Comment by thorsteneckel** [comment]
Hi @umarsheikh - we are currently in a pre release phase and we want to merge it in the release afterwards. Will review it next week, promise ✌️

**Comment by umarsheikh** [comment]
That works! Thanks!

**Comment by umarsheikh** [comment]
hello @thorsteneckel did u get a chance to review this yet?

**Comment by thorsteneckel** [comment]
Hi @umarsheikh - Not yet 😁  Zammad 2.3 was released just 14 hours ago. Next free time slot is reserved for Pull Requests and outstanding branch merging. Might be tomorrow but surely next week. I'll let you know.

**Comment by umarsheikh** [comment]
@thorsteneckel this actually works if you create a new column/attribute of type boolean from scratch, and then run a migration. if someone has already created a boolean column, and is yet to run the migration, then once you merge this PR, that boolean column will not be added when we run the migration, since the boolean type is already saved with incorrect data type. Once you merge this, i can send a second PR to ensure that if some attribute is saved already, we can still run the migration without needing to re edit it.

**Comment by thorsteneckel** [comment]
@muhammadn - And another ObjectManager Attribute issue wanted to get reviewed and fixed by you 👍

**Comment by muhammadn** [comment]
@umarsheikh Could you update your code to the latest `develop` branch since we did some changes then.

I am seeing the error yes with MySQL:
```
E, [2018-01-31T22:54:17.747567 #56559] ERROR -- : Mysql2::Error: Invalid default value for 'bool1': ALTER TABLE `tickets` ADD `bool1` tinyint(1) DEFAULT 'false' (ActiveRecord::StatementInvalid)
```

**Comment by umarsheikh** [comment]
@muhammadn sure, i will try and do it either today or tomorrow.

**Comment by umarsheikh** [comment]
@muhammadn ok, this branch is not up-to-date with latest develop. You can now check it out and merge it once you are sure it works.
so let me first describe how to test it:
- checkout this branch
- create new attribute
- run migration
- it shoudl work with boty mysql and postgres.

However, it will not work if:
- create new attribute
- checkout this code
- run migration
it will fail on run migration, since you created the attribute descriptions before checking out this code.

but if you have this code already, then anyone who now tries to create an attribute of type boolean, and then runs the migrations, it should work for him.

**Comment by muhammadn** [comment]
Thanks @umarsheikh . Merged. 🚀 There are some changes i did like params should be in a separate variable, fix some styling and added a test case for false boolean attributes to improve coverage.

You can actually find the coverage information at zammad/coverage/rcov

**Comment by umarsheikh** [comment]
You're welcome @muhammadn :)

**Pull request merged**
