### PR TITLE
Add option to disable default login

### PR DESCRIPTION
**Pull request by claudusd**
All of my users must be auth with SAML but some doesn't not understand it's must click on button SAML and use the login form. 
This PR add the option to hide the login form. If there are no third part application enable I display the form login to avoid to by lock.

image

And I change a little bit the CSS to center third part button. 

image

image

Translation are serve by translations.zammad.org ? Can I remove my commit about i18n ?

### CODE REVIEW

**Comment by mgruner** [comment]
@claudusd only about the i18n part - yes, please remove all changes to `i18n/*.po` files, they are managed by Weblate.

**Comment by claudusd** [comment]
@mgruner I remove my change about translation.

**Comment by claudusd** [comment]
Hi, can I do something about the  tag ``specification required `` ?

**Comment by dominikklein** [comment]
Hi @claudusd, thanks for your input for Zammad :-) we are currently checking this functionality inside of our Product-Team to clarify the next steps.

**Comment by joshuasprow** [comment]
I'm demoing Zammad for my organization and this is definitely a pain point. Even when I explicitly instruct users to ignore the username/password fields, they instinctively start typing.

**Comment by MrGeneration** [comment]
@joshuasprow please don't hijack PR or issues for your "I need this" situations.
If you wanna talk about this, please use the community for this kind of things.

**Comment by dominikklein** [comment]
@claudusd Thanks for your work. This PR will be part of the following feature: https://github.com/zammad/zammad/issues/4225

**Pull request closed without merging**
