### PR TITLE
Remove `sleep` from tests

### PR DESCRIPTION
**Pull request by corny**
Should not break anyting. There is more to clean up.

### CODE REVIEW

**Comment by corny** [comment]
Now another test fails. We really need [timecop](https://github.com/travisjeffery/timecop) to avoid race conditions and to remove all the `sleep` calls.

**Comment by martini** [comment]
JFI: There is a replacement of timecop with newer rails versions http://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html I try to rework this (later).

**Comment by corny** [comment]
Oh thanks, didn't know that before.

**Comment by corny** [comment]
current status:

`rake test:units` with `sleep`:
```
Finished in 751.106311s, 0.2450 runs/s, 5.7236 assertions/s.
184 runs, 4299 assertions, 0 failures, 0 errors, 0 skips
```

`rake test:units` with `travel`:
```
Finished in 391.915887s, 0.4695 runs/s, 10.9003 assertions/s.
184 runs, 4272 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by corny** [comment]
Tests were successful with MySQL, but not with PostgreSQL.

**Comment by corny** [comment]
Unfortunately it's still failing with PostgreSQL.

**Comment by martini** [comment]
Yes, on travis ci and my local installation 19 failing. I'm on it....

**Comment by monotek** [comment]
Wow. The test is 8 minutes faster now?! :)

**Comment by martini** [comment]
> Wow. The test is 8 minutes faster now?! :)

Not so fast. After a test is failing it skips other tests. :-/

**Comment by monotek** [comment]
But the mysql test seems fine. 
https://travis-ci.org/zammad/zammad/jobs/181880726
Was around 23 minutes before. Now its 15.

**Comment by martini** [comment]
That would be great!  😮

**Comment by martini** [comment]
Finally I got all done in develop (raised other bug which is fixed now). Speed is really significant faster!

Thanks @corny !

**Comment by corny** [comment]
Great work, thanks a lot to you!

**Pull request merged**
