### PR TITLE
Feat/chat hooks

### PR DESCRIPTION
**Pull request by ma-jahn**
From time to time it's required to interact with or react to status updates within the zammad chat application.

The aim of this Pull Request is to add certain hooks to the application, so the initiator can handle events like onReady or onCloseTransitionend.

Here a full list of hooks:

onReady
onCloseAnimationEnd
onError
onOpenAnimationEnd
onConnectionReestablished
onSessionClosed
onConnectionEstablished
onCssLoaded
this.chat = new ZammadChat({
  chatId: 2,
  host: host,
  cssUrl: cssUrl,
  debug: true,
  background: '#494d52',
  flat: true,
  idleTimeout: 1,
  idleTimeoutIntervallCheck: 0.5,
  inactiveTimeout: 2,
  inactiveTimeoutIntervallCheck: 0.5,
  waitingListTimeout: 1.2,
  waitingListTimeoutIntervallCheck: 0.5,
  onReady(data) {
    console.warn('onReady', data)
  },
  onCloseAnimationEnd(data) {
    console.warn('onCloseAnimationEnd', data)
  },
  onError(data) {
    console.warn('onError', data)
  },
  onOpenAnimationEnd(data) {
    console.warn('onOpenAnimationEnd', data)
  },
  onConnectionReestablished(data) {
    console.warn('onConnectionReestablished', data)
  },
  onSessionClosed(data) {
    console.warn('onSessionClosed', data)
  },
  onConnectionEstablished(data) {
    console.warn('onConnectionEstablished', data)
  },
  onCssLoaded(data) {
    console.warn('onCssLoaded', data)
  }
})

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hey @ma-jahn - I think I understood it too late. I wasn't aware this is a breaking change: User relying on the current implementation will be faced with errors once they update, because their implementation will refer to the current event API. So this is why I can't merge this. Do you have a proposal to resolve this?

**Comment by ma-jahn** [comment]
Hi @thorsteneckel, i'm afraid i don't understand why this would be a breaking change.
All of these hooks are intended to be optional.

You can use the chat just like before but if you want to add custom logic you can provide one of these hooks.

But maybe i'm not aware of certain processes :)

**Comment by thorsteneckel** [comment]
Sorry my bad 😞 Everything is clear now. The change is currently running on our internal CI and will be merged soon 🚀 Thanks again

**Comment by ma-jahn** [comment]
Thank you very much for having another look at it.
Have a great weekend :)

Thorsten <notifications@github.com> schrieb am Fr., 17. Jan. 2020, 16:11:

**Comment by thorsteneckel** [comment]
Thanks again! Merged with the commit above. Closing now. Enjoy your weekend 🕺

**Pull request closed without merging**
