### PR TITLE
include rsync -a into variable RSYNC_ADDITIONAL_PARAMS, rename RSYNC_…

### PR DESCRIPTION
**Pull request by klml**
…ADDITIONAL_PARAMS to RSYNC_PARAMS

Enables configuration _all_ rsync  params, also `-a`. And you have all rsync  params in one place.

my current usecase: I want to expand `-a` to `-rlptgoD`, so I can remove `-t preserve modification times` . This is needed to avoid rsync setting time on directory `/opt/zammd/` , which is still owned by root.

### CODE REVIEW

**Comment by klml** [comment]
@monotek you [introduced RSYNC_ADDITIONAL_PARAMS](https://github.com/zammad/zammad/blame/develop/contrib/docker/docker-entrypoint.sh#L25), so I would be happy if you could rate my PR, thx ;)

**Review by monotek — COMMENTED** [review]
Not sure if this is wanted as it would be a breaking change for existing users and we cant reflect that via the image version easily.

**Comment by klml** [comment]
@monotek sorry I missed backwardcompatibility, so I just preseved RSYNC_ADDITIONAL_PARAMS 18b43b9af5871bf846c8ccb4ade43201f952d68d but for me this not really well formed.

For my problem, preventing time modification on `/opt/zammad`, I have found another workaround with an extraEnv `ZAMMAD_DIR="/opt/zammad/*"`, also not nice, but hope this will do the job.

thx

**Comment by klml** [comment]
> ZAMMAD_DIR="/opt/zammad/*"

this idea was missleading and did not work with rsync.

After reading `man rsync ` ;), I tried with `--no-times` and `--omit-dir-times`, both worked with exec.

```
klml@nbo123456 capc/zammad [0] : ~/develop/zammad
$ oc exec zammad-0 -c zammad-init -- rsync -a --no-perms --no-owner --delete --exclude 'public/assets/images/*' --exclude 'storage/fs/*' "/tmp/zammad/" "/opt/zammad"
rsync: [generator] failed to set times on "/opt/zammad/.": Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
command terminated with exit code 23
klml@nbo123456 capc/zammad [23] : ~/develop/zammad
$ oc exec zammad-0 -c zammad-init -- rsync -a --omit-dir-times --no-perms --no-owner --delete --exclude 'public/assets/images/*' --exclude 'storage/fs/*' "/tmp/zammad/" "/opt/zammad"
klml@nbo123456 capc/zammad [0] : ~/develop/zammad
$ oc get po zammad-0 -o yaml | yq .status.initContainerStatuses
...

    "name": "zammad-init",
    "ready": true,
...

```

But not with env `RSYNC_ADDITIONAL_PARAMS` ;(

But this PR is not needed anymore.

**Comment by klml** [comment]
I fixed "rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]" with [extraRsyncParams](https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml)

```
zammadConfig:
  initContainers:
    zammad:
      extraRsyncParams: "--no-perms --no-owner --no-times"
```

[extraEnv](https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L284) `RSYNC_ADDITIONAL_PARAMS` does not work.

**Pull request closed without merging**
