### PR TITLE
prevent "CSRF token verification failed!" error

### PR DESCRIPTION
**Pull request by amigthea**
the ssl configuration was incomplete, I implemented the necessary parameter

### CODE REVIEW

**Comment by MrGeneration** [comment]
Sorry, but we decided that we will not provide such workarounds within the default configuration. 
You can read more on the reasons why here:
https://github.com/zammad/zammad/issues/2829#issuecomment-757861101

The docker-compose in fact already supports this:
https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh

See also:
* https://docs.zammad.org/en/latest/getting-started/configure-webserver.html
* https://docs.zammad.org/en/latest/install/docker-compose/environment.html

**Comment by amigthea** [comment]
but that's a loop!

1) the default installation is on http
2) to switch to https on docker compose we need to provide an additional .conf file because the default one (/etc/nginx/sites-enabled/default) is overwritten at every container restart, making your entrypoint workaround useless because it will not apply to the additional ssl .conf
3) the default template of the ssl .conf file don't provide that mandatory parameter
4) ???

**Comment by MrGeneration** [comment]
Nevermind me, sorry. You're right. The directive is absolutely missing while it's available (and required) for running the instance without issues. No idea why this was never added. 

I was going to reference another reverted PR but saw that variables are different.

@mantas could you please take over?

**Comment by mantas** [comment]
@monotek do you mind to take a quick look?

**Review by monotek — APPROVED** [review]

**Comment by monotek** [comment]
LGTM

**Comment by mantas** [comment]
Hi @Azertooth,

Your PR is now merged with the commit above. Thank you for your contribution!

**Pull request closed without merging**
