### PR TITLE
[REVIEW] Fix/trigger variables missing

### PR DESCRIPTION
**Pull request by rosscdh**
AS per https://github.com/zammad/zammad/issues/2716

I need some guidance as to where to source the `::` data from to pass into the locals arg.

### CODE REVIEW

**Comment by rolfschmidt** [comment]
Hi @rosscdh ,

thanks for your contribution! I merged it 👍

**Comment by rosscdh** [comment]
@rolfschmidt will this also be in 3.6? Thanks

**Comment by rolfschmidt** [comment]
@rosscdh yupp.

**Comment by rosscdh** [comment]
Great thanks!

**Comment by dominikklein** [comment]
The commit d4dfd750b722071c9b8f1ad4a2b7b59f82656966 has the wrong relation, it's for the following pull request: https://github.com/zammad/zammad/pull/3682

**Pull request closed without merging**
