### PR TITLE
added variable to deactivate IPv6

### PR DESCRIPTION
**Pull request by jv-barsuk**
Zammad docker-compose setup fails to start when IPv6 is not activated on the source system, because nginx and puma tries to listen on IPv6 addresses.

https://community.zammad.org/t/docker-setup-and-resources/12305

### CODE REVIEW

**Comment by dominikklein** [comment]
@mgruner Maybe something you can check?

**Review by mgruner — CHANGES_REQUESTED** [review]
Hello @jv-barsuk, thank you for your contribution. Right now I have concerns regarding this MR, mostly because it changes the behaviour. All existing systems which have ZAMMAD_IPV6 not set will switch to IPv4 only. That is not acceptable.

To change this, I would suggest that you update the PR as follows:

- use a variable `ZAMMAD_DISABLE_IPV6` instead which is not set by default
- make a separate `sed` call to remove the listen directive only if this variable is set, rather than a non-matching pattern
- change the puma invocation accordingly

With that, we'd have backwards compatible behaviour. What do you think?

**Comment by mgruner** [comment]
I will close this PR for now. Please feel free to reopen / open another one with the updates. Thank you very much!

**Comment by jv-barsuk** [comment]
I created a new pull request with your suggested changes, which can be found here: https://github.com/zammad/zammad/pull/4951

**Pull request closed without merging**
