### PR TITLE
Fixes #2669: Pressing "Cancel" when separating a ticket doesn't close tab.

### LINKED ISSUE #2669: Pressing "Cancel" when creating a new ticket or separating an existing ticket doesn't close tab
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): Docker
* Elasticsearch-Version: 5.6.14
* Operating system: Ubuntu 18.04
* Browser: FF68, GC75

### Expected behavior:

* Tab is closed and ticket creation aborted

### Actual behavior:

* Ticket creation tab remains open 

### Steps to reproduce the behavior:

* Open new ticket dialog or press *Split* on a ticket
* On the ticket creation page press *Cancel*

Yes I'm sure this is a bug and no feature request or a general question.

### PR DESCRIPTION
**Pull request by dvuckovic**
Fixes #2669.

Current ticket creation screen task will be implicitly closed when canceled.

### CODE REVIEW

**Comment by mantas** [comment]
@dvuckovic looks great!

Could you redo the test as RSpec/Capybara? We're slowly migrating our tests to RSpec and it'd be great to not add new legacy tests :)

**Comment by dvuckovic** [comment]
@mantas I'd be happy to!

Could you please perhaps point me to a sample test in this format? I have _zero_ experience with this, and would appreciate a friendly nudge :)

Also, if it's not too much trouble, perhaps a sample command how to run a certain test of this type? Documentation is somewhat scarce on this topic.

Thanks for your help!

**Comment by mantas** [comment]
Sure!

This spec may be a good starting point https://github.com/zammad/zammad/blob/develop/spec/system/ticket/zoom_spec.rb

Following command would run above test:

`bundle exec spec/system/ticket/zoom_spec.rb`

This test uses compiled assets. Run following to make sure latest `.coffee` changes are picked up:

`RAILS_ENV=test bundle exec rake assets:precompile`

Following command would ensure you've same DB contents as in CI server:

`RAILS_ENV=test bundle exec rake db:drop db:create zammad:ci:test:prepare`

Feel free to ask if you have any questions

**Comment by martini** [comment]
I also have a functional question: Is there a warning if there is a content in the form? A warning like you click on close tab in the task bar?

image

**Comment by dvuckovic** [comment]
@mantas Thanks a lot for your help, it worked perfectly! I knew I was missing some command to add all that test data :)

Just being pedantic, the run command above is missing the `rspec` task, this is the working one:

```
bundle exec rspec spec/system/ticket/zoom_spec.rb
```

It's even possible to run just a specific context/test case by including the line number where it starts:

```
bundle exec rspec spec/system/ticket/zoom_spec.rb:1070
```

In the same fashion, I added a couple of test cases to an existing RSpec/Capybara file, please check it out when you get a chance. Thanks again!

@martini You are absolutely right: the confirmation dialog is NOT shown when canceling the action via the cancel button. I'll look into setting up a similar handler as when closing the task, if possible. The question is whether this is a systemic issue, I have seen this button in many other screens. Perhaps a good spot to rethink the approach and refactor the code if that's indeed the case. Thanks!

**Comment by thorsteneckel** [comment]
@mantas - would you mind taking over?

**Comment by thorsteneckel** [comment]
Closed with https://github.com/zammad/zammad/commit/2001ac6968faaacf0db99be40781b94a9d1c07b0 - thanks for your contribution!

**Pull request closed without merging**
