### PR TITLE
Added Sina-Weibo OAuth2

### LINKED ISSUE #1465: support Weibo OAuth2 login
Sina Weibo social media as Twitter-Like in China. I'll add Weibo login for Zammad. About Sina Weibo more: http://ir.weibo.com/

### PR DESCRIPTION
**Pull request by NeverMin**
Hi @thorsteneckel , please review, if have any question please let me know, thank you for your time.

gem: [omniauth-weibo-oauth2](https://github.com/beenhero/omniauth-weibo-oauth2)

WeiboID for test:
https://test.zammad.org.cn
WeiboID: echo "MTg5MTM1MjAzODMK" | base64 -d
Password: echo "WmFtbWFkVEVTVDIwMTcK" | base64 -d

Login UI:
login

Link Account:
account

User Information:
image

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @NeverMin - as stated in #1451 and #1435 we are focusing on creating a plugin system for further Omni-Auth strategies since it bloats our core dependencies and increases the maintenance overhead. This should be implemented as an addon in the future. Would be great to see it then! Therefore I have to close this pull request for now.

**Comment by NeverMin** [comment]
Hi @thorsteneckel , thank you for your respond, this is my reasons:

1. We can't use Twitter, Google, Facebook in China, add Weibo authentication will be great for China Zammad users;

2. I understand what is "maintenance overhead", as you can see in the [Demo](https://test.zammad.org.cn), in fact, I have completed another WeChat third-party authentication, I think WeChat should be as an addon;

3. Out-of-box experience for China users;

4. Many of the Chinese authors' GEMs are in disrepair, because zammad requires omniauth-weibo-auth0, so I have taken over this gem.

Can you think twice please? If there are any concerns, please let me know, thank you again.

**Comment by thorsteneckel** [comment]
Thanks to making things clear. I wasn't aware of the importance for our fellow Chinese people. We'll do as you proposed adding this PR to the Zammad core and releasing the WeChat PR as an addon.

**Comment by NeverMin** [comment]
Hi @thorsteneckel , so nice to hear your voice. :tada: :smiley:

**Comment by thorsteneckel** [comment]
Merged with the commit above. Thanks for your contribution!

**Pull request merged**
