### PR TITLE
Uniform two factor string translation

### PR DESCRIPTION
**Pull request by maxxer**
The *Try another method* string is being translated with only the *T* capital all around except here

### CODE REVIEW

**Comment by mgruner** [comment]
@maxxer @dominikklein `Try Another Method` looks ok to me as title case which seems appropriate in a heading.

**Comment by dominikklein** [comment]
I think the problem is that we have two places with the same string, but different first letters.

**Comment by sheremet-va** [comment]
> @maxxer @dominikklein `Try Another Method` looks ok to me as title case which seems appropriate in a heading.

There is a CSS property for that (`text-transform: capitalize`), shouldn't we just use it to keep translation consistent? Or it doesn't work great with other languages?

**Comment by dominikklein** [comment]
> There is a CSS property for that (text-transform: capitalize), shouldn't we just use it to keep translation consistent? Or it doesn't work great with other languages?

@dvuckovic @mgruner what do you think about this question?

From the current string perspective, I think title is missing it in this file: app/frontend/apps/mobile/pages/login/views/Login.vue:133

**Comment by dvuckovic** [comment]
I guess we could use CSS for this, as it's presentational, sure. But using it just in one instance is probably not a good idea: it's confusing and prone to breakage. Probably a good point for the desktop rewrite though 😄

**Comment by maxxer** [comment]
> There is a CSS property for that (`text-transform: capitalize`), shouldn't we just use it to keep translation consistent? Or it doesn't work great with other languages?

Indeed, that's not correct for the Italian language. I don't know about UI or graphical appearance, but the language itself doesn't contemplate the use of all capitalized words for a title, AFAIK.

**Comment by mgruner** [comment]
I agree with @maxxer. We must leave this to the translators, that's why the source strings must be as correct as they can be.

**Comment by dominikklein** [comment]
Then this place needs to be changed to Title-Case: `app/frontend/apps/mobile/pages/login/views/Login.vue:133` to align the two use cases.

**Comment by dominikklein** [comment]
@maxxer Many thanks for bringing this up, it's now aligned with the following commit: https://github.com/zammad/zammad/commit/ecb60a73e8444d0611a491b140cc54b111d2c08e

**Pull request closed without merging**
