### PR TITLE
issue: #2596, fixed chat header's height

### PR DESCRIPTION
**Pull request by NeverMin**

### CODE REVIEW

**Comment by MrGeneration** [comment]
Hey @mrflix could you please check this when you find some spare time? Thank you :)

**Comment by mrflix** [comment]
looks good - exactly what's needed to fix it.

**Review by mrflix — APPROVED** [review]

**Comment by thorsteneckel** [comment]
@SummerStorm - could you please run this through our CI and create am MR?

**Comment by SummerStorm** [comment]
> @SummerStorm - could you please run this through our CI and create am MR?

Yep, already done: https://git.znuny.com/zammad/zammad/commits/private-pr2597

CI not passing though due to unrelated isues, unfortunately. I'll submit a MR as soon the CI is green again.

**Comment by martini** [comment]
closed by accident - re-open

**Comment by thorsteneckel** [comment]
Applied via https://github.com/zammad/zammad/commit/ebe053efca7bc7a2a03631b6b7af5272253cca34 - thanks a to @NeverMin 😍 Closing now.

**Pull request closed without merging**
