### PR TITLE
Chinese(zh-cn) email template localisation

### PR DESCRIPTION
**Pull request by NeverMin**
added git ignore files:
/config/locales.yml
/config/translations/
/public/assets/doorkeeper/

### CODE REVIEW

**Comment by NeverMin** [comment]
Let me add zh_TW later.

**Comment by martini** [comment]
Ups. Can I merge the PR for zh-cn?

**Comment by NeverMin** [comment]
Hi Martin,

I will submit new PR today, include zh-cn and zh-tw.


-Never

2017-03-16 9:31 GMT+08:00 Martin Edenhofer <notifications@github.com>:

**Comment by martini** [comment]
oh yeah! :)

**Pull request closed without merging**
