### PR TITLE
2296 - Customer and org ticket to be sorted created_at desc

### LINKED ISSUE #2296: Ticket list in overview of customer and organisation random order
### Infos:

* Used Zammad version:  2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* When viewing the list of open and closed tickets of customers and/or organisations, the list should have a chronological order.

### Actual behavior:

* When viewing the list of open and closed tickets of customers and/or organisations, the list has an absolute random order.

### Steps to reproduce the behavior:

* create some tickets for a customer
* take a look on the open/closed tickets within user information.

DEV-Information:
Original ordering should be: "created_at: :desc"
Parameters are missing: https://github.com/zammad/zammad/blob/develop/app/controllers/concerns/ticket_stats.rb#L7

image

image

Yes I'm sure this is a bug and no feature request or a general question.

This came from Ticket#1029435 

Edit: Fixed image

### PR DESCRIPTION
**Pull request by yasirazgar**
Fixes https://github.com/zammad/zammad/issues/2296
Previously it was sorted by updated_at desc, changed it to order by created_at desc.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @yasirazgar - thanks for your contribution! Could you please add a browser test for it?

**Comment by yasirazgar** [comment]
Hi @thorsteneckel sorry, I am not sure where to add the tests for this change, can you point me to a file where test for this change will fit perfectly.

**Comment by thorsteneckel** [comment]
These two tests should get extended:

https://github.com/zammad/zammad/blob/develop/test/browser/agent_user_profile_test.rb
https://github.com/zammad/zammad/blob/develop/test/browser/agent_organization_profile_test.rb

EDIT:
A request spec would be great, too: https://github.com/zammad/zammad/tree/develop/spec/requests

**Comment by yasirazgar** [comment]
@thorsteneckel I have added request spec is that enough, 
I am unable to run browser tests in my local getting some errors, is there any set up guide for this.

**Comment by thorsteneckel** [comment]
Hi @yasirazgar - Thanks! Looks like your changes fail on TravisCI. Could you please resolve this? Other from that I think that we don't need dedicated browser tests for this. The request specs are sufficient 👍 

@rlue - could you please take over from here on/after the TravisCI issue is resolved?

**Comment by rlue** [comment]
@yasirazgar, I took a quick peek at [the failing Travis build](https://travis-ci.org/zammad/zammad/jobs/444040947); here's a quick summary:

1. Rubocop failures

   ```
   spec/requests/ticket_spec.rb:2092:15: W: Rails/ActiveRecordAliases: Use update instead of update_attributes.
         ticket2.update_attributes(title: 'Some title')
                 ^^^^^^^^^^^^^^^^^
   spec/requests/ticket_spec.rb:2095:11: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
         get "/api/v1/ticket_stats", params: { organization_id: organization.id, user_id: customer.id }, as: :json
             ^^^^^^^^^^^^^^^^^^^^^^
   ```

2. Unit tests

   ```
   Failures:
     1) Ticket stats orders tickets based on created_at desc
        Failure/Error: expect(json_response['user']['open_ids']).to eq([ticket3.id, ticket2.id, ticket1.id])
        
          expected: [244, 243, 242]
               got: [242, 243, 244]
        
          (compared using ==)
        # ./spec/requests/ticket_spec.rb:2099:in `block (3 levels) in <top (required)>'
   Finished in 4 minutes 29.9 seconds (files took 7.42 seconds to load)
   1183 examples, 1 failure, 1 pending
   Failed examples:
   rspec ./spec/requests/ticket_spec.rb:2084 # Ticket stats orders tickets based on created_at desc
   ```

Looking forward to getting this merged after these have been addressed!

**Comment by yasirazgar** [comment]
@thorsteneckel @rlue fixed rubocop and test failures.

**Comment by rlue** [comment]
This was merged with some modifications as 66e8d58. Thanks for your contribution @yasirazgar!

**Pull request closed without merging**
