### PR TITLE
Added relative pending_time to Macro/Trigger/Scheduler Functionality

### PR DESCRIPTION
**Pull request by fleverest**
Issue #864

Closed old pull request and opened this one. This includes a change to the client which allows selecting of relative dates for the pending_time attribute.

For example:
image

Will set the pending_time for the ticket to precisely 7 days from now.

There is an issue with how the row is rendered in this case, but as this is a popular feature request I think the benefits outweigh the rendering problem. I basically replicated the models and controllers for Triggers, but the views are different between the two and I'm not sure I will be able to fix them to look suitable.

### CODE REVIEW

**Comment by fleverest** [comment]
Also works for triggers now. Ruby classes were a bit confusing so it took me a long time to write these 26 lines...

**Comment by MrGeneration** [comment]
Thank you so much for your effort!
We're currently having quite some stuff to do, so verification and QA might take it's time. 

But we'll have a look 💪

**Comment by fleverest** [comment]
I understand, it's fine.
I'll continue to work on this anyway to increase the chances of this PR being accepted.

I realized I still need to implement handler for Scheduler before this is finished, and also fix the styling (just needs a horizontal tag on one element but I need to learn how to edit js/app/views).

**Comment by MrGeneration** [comment]
I added `WIP: ` to the PR title.
This will give you the time you need to finish your PR accordingly.

If you're ready to go, please remove `WIP:` so we know you're ready to go and we'll then have a look. :-)

Thanks!

**Comment by fleverest** [comment]
_Improved_ formatting:
image
image

Tested Scheduler and it works fine without any changes - I assume it uses the same perform method as the triggers:

I created this scheduler to test:
image

And, well...
image

It works!

**Comment by MrGeneration** [comment]
Wow, thank you so much for your effort -again- !!
We'll have a look as soon as possible. :-)

**Comment by thorsteneckel** [comment]
Hello and thanks @fleverest - what a great job! We really want to add these changes. However, we need to add some tests to it to protect us from regressions now and in the future. There are some other tests for other `perform` actions: https://github.com/zammad/zammad/blob/22a25f266daf5948c8fc751a003139bebbc1157b/spec/models/ticket_spec.rb#L122-L213

Would you mind adding some for the functionality you added in the same way? JFI: You can execute the test by running:

```bash
export RAILS_ENV=test
script/bootstrap.sh && echo '' > log/test.log
bundle exec rspec spec/models/ticket_spec.rb
```

Additionally we'll need some capybara/browser tests. However, it's much more advanced to write those so we will do that part then. For the record:

* Macro: Create and execute macro via browser (separated tests!)
* Trigger: Create and verify (via reload)
* Scheduler: Create and verify (via reload)

Looking forward to hear from you 🚀

**Comment by fleverest** [comment]
Thanks @thorsteneckel, I'll work on it tonight after work if I get the chance :)

**Comment by fleverest** [comment]
The ruby perform test works. To be clear, only the browser tests remain now?

**Comment by thorsteneckel** [comment]
WOW 😍Generally yes, only the browser tests remain now. However, I saw that you changed from string keys (`value['range']`) to symbol keys (`value[:range]`). Do you mind elaborating why? As I looked around other existing code I saw that there are string based keys used. I'd prefer a consistent code here to prevent confusion and bugs.

I'll talk to the devs for adding the browser tests 👍

**Comment by fleverest** [comment]
I switched to symbol keys because they resolved an error I was having writing my test (second part of my perform hash was using ':' rather than '=>') But this was just an oversight. I'll rebase and force push the changes without using symbol keys.

**Comment by fleverest** [comment]
Please forgive my messy git habits - this is my first open source contribution.

**Comment by thorsteneckel** [comment]
No worries :) I also have a git history spleen ;) @mantas will take care of the browser tests and run your changes through our internal CI 🚀

**Comment by fleverest** [comment]
That’s great news, please let me know if changes need to be made to this PR

**Comment by fleverest** [comment]
Just pushed a minor update that prevent an misleading "Ticket not updated" warning whenever you close the ticket after applying the perform method. This was because the UI does not have a seconds selector and the perform method sets pending time exact to the second.

**Comment by mantas** [comment]
Hi @fleverest ,

What are exact steps to reproduce the "Ticket not updated" warning? What macro configuration would trigger it?

I was testing it without zero-ing seconds and it seemed fine.

**Comment by fleverest** [comment]
Hello @mantas,

Here's how to reproduce it (prior to my last two commits):
Create the following macro:
image
Open the "welcoming" ticket and execute the macro.
Finally, close the ticket by exiting it in the left sidebar.
You get this message:
image
At this point, you can observe the following output from the browser console:
```
>> App.Ticket.first().pending_time
<-"2020-02-11T07:50:39.075Z"
```
In the rails console, this time is also saved in the ticket attributes - so everything acts fine except for the UI.
If you press 'Update' at this point, it will round down the `pending_time` attribute:
```
>>App.Ticket.first().pending_time
<-"2020-02-11T07:50:00.000Z"
```
So my last two commits simply changed the input date from the macro perform to round the seconds and milliseconds. This change worked as expected and now the "Ticket has changed" warning no longer appears.

**Comment by fleverest** [comment]
@MrGeneration Is there a change we could add a Prioritized by payment tag to this PR? I believe the underlying issue #864 was prioritized mid last year - I'm unsure if this is how you organize priorities in your workflows

**Comment by mantas** [comment]
Hi @fleverest it is currently waiting in QA queue. I just checked it and there seems to be no pending issues, but it still needs one final look from @thorsteneckel . Unfortunately it didn't make it to 3.3, but I'm positive it will make it to next release.

Sorry for the delay.

**Comment by tobiashuste** [comment]
Very valuable contribution :rocket: Are there any updates on your plans since it seems to have missed 3.4 as well?

**Comment by mantas** [comment]
Unfortunately it's still stuck in QA.

@thorsteneckel can we promise we'll include it in 3.4.1? :)

**Comment by thorsteneckel** [comment]
Update from my review: We found some bugs @mantas is about to address.

**Comment by fleverest** [comment]
@mantas What are the bugs that were discovered? I'd like to hear of them. I'd really like to upgrade to the next release once this PR has been accepted.

**Comment by thorsteneckel** [comment]
Hey @fleverest - thanks again for providing the PR! It's finally merged 🚀  Just for completeness: The issues were

- The `static` calendar picker does not load after switching to `relative` and back to `static`
- The time selection field (`hh::mm`) is too wide and looks strange
- The form validations marks the relative date selection as an error even before I had the chance to select something

@mantas correctly pointed out that the second and third issue were/are general Zammad issues. We will address those in dedicated commits which are already ready for review and waiting for me 🙈 

EDIT:
The first one was resolved by @mantas in the meantime 🙇

**Pull request closed without merging**
