### PR TITLE
Fixes #849 - Allow additional usage of Ticket Number in (Zoom) URL

### LINKED ISSUE #849: Allow additional usage of Ticket Number in (Zoom) URL
### Infos:

* Used Zammad version: 1.3.x
* Operating system: Debian
* Browser + version: Chrome

### Expected behavior:

* Ticket Number in URL is correct

### Actual behavior:

* Ticket Number (ID) in URL is different to the ticketnumber

### Steps to reproduce the behavior:

* The Ticket ID 279 is missing:
> SELECT id, number, title FROM tickets ORDER BY id;
 277 | 35277  | Probleme mit Outlook
 278 | 35278  | Probleme mit Outlook TEST
 280 | 35279  | Defekte Festplatte im Server
 281 | 35280  | Fristverlängerung online
 282 | 35281  | NB191 Tunnel zu iSource offline

image

We haven't deletet any ticket manually or somthing else.
Any idea how to fix this?

### PR DESCRIPTION
**Pull request by Stubenhocker1399**
Hi! :smile: 

I've implemented a ticket linking functionality to Zammad as requested in this [community forum post](https://community.zammad.org/t/open-detail-page-for-ticket-with-ticket-number-via-url/9197).

Visiting #ticket/number/xxxxx automatically redirects to the correct zoom view.

I wasn't able to test my tests as I don't have Selenium set up, hope they work as expected. :sweat_smile:

### CODE REVIEW

**Comment by rolfschmidt** [comment]
rel https://github.com/zammad/zammad/issues/849

**Comment by rolfschmidt** [comment]
Hi @Stubenhocker1399 ,

I think this code will only work for tickets which are already present in the frontend UI. To solve this you would need to do an ajax request (`App.Ajax.request`) to the `/v1/tickets/search` endpoint.

here an example of an ajax request,
https://github.com/zammad/zammad/blob/1aa8c9e43a2f403bc0688a49894f097195b8bd69/app/assets/javascripts/app/lib/app_post/global_search.coffee#L33

here the endpoint 
https://github.com/zammad/zammad/blob/1aa8c9e43a2f403bc0688a49894f097195b8bd69/app/controllers/tickets_controller.rb#L455

You could try to use a post request with a condition hash (then it also works without elastic search):

``` 
condition: { 'ticket.number' => { operator: 'is', value: '71001' } }
```

grafik


this should return the ticket id and the assets which can be loaded via (`App.Collection.loadAssets(data.assets)`) and then you can find your ticket and redirect.

**Comment by Stubenhocker1399** [comment]
@rolfschmidt Regarding the
> I think this code will only work for tickets which are already present in the frontend UI.

is there some easy way to achieve that state? Because even when disabling all overviews the current code worked fine for me.

I'm not too familiar with what decides a ticket being "present in the frontend UI". Seems to me that it'd be preferable to use this data source first than an extra request if possible.

**Comment by SamuelPlentz** [comment]
Thanks to everyone involved to make that happen in Zammad 5.2.2! (#849)

FYI: To use this really nice feature you have to use:
```
/#ticket/zoom/number/10123
```

There were several proposals of the syntax that don't work:
```
/#ticket/number/10123
/#ticket/external/10123
```

**Pull request closed without merging**
