### PR TITLE
Chat: Remove agent status from chat toggle

### PR DESCRIPTION
**Pull request by silsha**
The chat window is currently toggled when clicking on the agent status, which also ends the conversation.

This PR moves the agent status outside the `js-chat-toggle` class.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @mrflix - could you please review this PR? Thanks!

**Comment by silsha** [comment]
@mrflix @thorsteneckel Any news on this?

**Comment by thorsteneckel** [comment]
Hi @silsha - thanks again for your PR. We were busy with the release of Zammad 2.5 but will review the PRs in the next days. Yours will be reviewed next week by @mrflix and me. We'll let you know

**Comment by mrflix** [comment]
Thanks for the chat @silsha. I directly edited the source files and bound a stopPropagation to the click on the status to prevent the chat from closing.

**Pull request closed without merging**
