### PR TITLE
Fixes: #4682 - After update to Zammad 6.0.0 brand logo is broken (only docker version)

### PR DESCRIPTION
**Pull request by mgruner**

### CODE REVIEW

**Comment by mgruner** [comment]
@monotek can you check please? This should solve the issue by making sure the nginx container also has the custom logo files. Worked for me locally.

**Comment by monotek** [comment]
Can you test it?
I'm realy busy right now.

**Comment by mgruner** [comment]
@monotek it did work for me.

**Review by monotek — APPROVED** [review]

**Comment by pgassmann** [comment]
this change is only on the stable branch, but not on the (default) develop branch. 

For that to work, the nginx container also needs the credentials for postgres. This is currently missing in the zammad-docker-compose project. See also https://github.com/zammad/zammad-docker-compose/pull/357

**Pull request closed without merging**
